# Welcome to Jekyll!
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

################################################################################
# Basic Site Settings
################################################################################

locale: "en-US"
site_theme: "default"
title: "Amit Singha - Academic Website"
title_separator: "-"
name: &name "Amit Singha"
description: &description "PhD Student researching AI driven mmWave-based wireless systems security & Adversarial ML at Purdue University (Indianapolis)."
url: "https://singpurdue.github.io"       # the base hostname & protocol for your site
baseurl: ""                               # the subpath of your site, e.g. "/blog" if needed
repository: "singpurdue/singpurdue.github.io"

################################################################################
# Site Author
# The following control what appear in the sidebar profile (and various places).
# If a field is blank, its icon and link won't appear. 
################################################################################

author:
  # Basic info
  avatar: "images/profile.jpg"  # e.g. "images/profile.png" if you place a profile pic there
  name: "Amit Singha"
  pronouns:              # e.g. "he/him" or "she/her" if you like
  bio: "PhD Student in Electrical and Computer Engineering focusing on mmWave-based wireless systems, adversarial machine learning, and information security."
  location: "Indianapolis–46202, USA"
  employer: "Purdue University"
  uri:                   # If you have a personal website other than GitHub Pages, you can place it here.
  email: "singha3@purdue.edu" 
  
  # Academic websites
  arxiv:                 # e.g. "https://arxiv.org/a/abc123"
  googlescholar: "https://scholar.google.com/citations?user=X7PsN4gAAAAJ"
  impactstory:           
  orcid:                 # e.g. "https://orcid.org/0000-0001-2345-6789"
  semantic:              
  pubmed:                # e.g. "https://www.ncbi.nlm.nih.gov/pubmed/?term=YourName"
  researchgate: "https://www.researchgate.net/profile/Amit-Singha-3"
  scopus:                # e.g. "https://www.scopus.com/authid/detail.uri?authorId=..."
  
  # Repositories and software development
  bitbucket:
  codepen:
  dribbble:
  github: "SINGHAMIT1"   # GitHub username (not a full URL). The template auto-links.
  kaggle:
  stackoverflow:
  
  # Social media
  bluesky:               # e.g. "bsky.app/profile/yourhandle"
  facebook:
  flickr:
  foursquare:
  goodreads:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin: "singha-amit"  # LinkedIn username or vanity URL slug
  mastodon:
  medium:
  pinterest:
  soundcloud:
  steam:
  telegram:
  tumblr:
  twitter:               # e.g. "YourTwitterHandle"
  vine:
  weibo:
  wikipedia:
  xing:
  youtube:
  zhihu:

################################################################################
# Publication Category Labels
################################################################################

publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

################################################################################
# Site Settings
################################################################################

teaser:                  # filename of teaser fallback image in /images/ e.g. "500x300.png"
breadcrumbs: false       # true or false
words_per_minute: 160
future: true
read_more: "disabled"    # "enabled" or "disabled"
talkmap_link: false
comments:
  provider:              # false, "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts: 5
    colorscheme: "light"

staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

atom_feed:
  hide: false
  path: 

################################################################################
# SEO Related (optional)
################################################################################

google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

################################################################################
# Social Sharing
################################################################################

twitter:
  username: &twitter

facebook:
  username:
  app_id:
  publisher:

og_image:

social:
  type:
  name:
  links: []  # An array of links to social media profiles if desired

################################################################################
# Analytics (optional)
################################################################################

analytics:
  provider: "false" # false, "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id:

################################################################################
# Reading/Building
################################################################################

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

################################################################################
# Collections
################################################################################

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

################################################################################
# Defaults
################################################################################

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

################################################################################
# Sass/SCSS
################################################################################

sass:
  sass_dir: _sass
  style: compressed

################################################################################
# Outputting
################################################################################

permalink: /:categories/:title/
# paginate: 5
# paginate_path: /page:num/
timezone: Etc/UTC

################################################################################
# Plugins
################################################################################

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

################################################################################
# Archives
################################################################################

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

################################################################################
# HTML Compression
################################################################################

compress_html:
  clippings: all
  ignore:
    envs: development
